**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

# I. NumPy.

0. Імпортувати numpy загальноприйнятим способом.

---



In [2]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [1]:
import numpy as np

grades = [88, 51, 71, 65, 31, 100, 95, 89]

grades_array = np.array(grades)

print(grades_array)

[ 88  51  71  65  31 100  95  89]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [3]:
import numpy as np

prices = [
    [15.5, 42.0, 32.8, 120.0],
    [16.0, 40.5, 33.5, 125.0],
    [14.8, 41.2, 31.9, 118.5]
]

prices_matrix = np.array(prices)

print(prices_matrix)

[[ 15.5  42.   32.8 120. ]
 [ 16.   40.5  33.5 125. ]
 [ 14.8  41.2  31.9 118.5]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [4]:
grades_dtype = grades_array.dtype
prices_dtype = prices_matrix.dtype

print(grades_dtype)
print(prices_dtype)

int64
float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
grades_shape = grades_array.shape
prices_shape = prices_matrix.shape

print(grades_shape)
print(prices_shape)

(8,)
(3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [6]:
import numpy as np

sales_profit = np.linspace(0, 1000.50, 7)

print(sales_profit)

[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [7]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

h_stack = np.hstack((array1, array2))

v_stack = np.vstack((array1, array2))

print(h_stack)
print(v_stack)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [8]:
import numpy as np

def transpose_array(arr):
    """
    The function takes a 2D array as input and transposes it.

    Parameters:
    arr (numpy.ndarray): The input array.

    Returns:
    numpy.ndarray: The transposed array.
    """
    return arr.reshape(arr.shape[1], arr.shape[0])

matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = transpose_array(matrix)

print(matrix)
print(transposed_matrix)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [9]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

addition_result = array1 + array2
subtraction_result = array1 - array2
scalar_multiplication_result = array1 * 2
elementwise_multiplication_result = array1 * array2
matrix_multiplication_result = np.dot(array1, array2)

print("Element-wise addition:\n", addition_result)
print("Element-wise subtraction:\n", subtraction_result)
print("Multiplication by scalar:\n", scalar_multiplication_result)
print("Element-wise multiplication:\n", elementwise_multiplication_result)
print("Matrix multiplication:\n", matrix_multiplication_result)

Element-wise addition:
 [[ 6  8]
 [10 12]]
Element-wise subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication by scalar:
 [[2 4]
 [6 8]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [1]:
import numpy as np


matrix = np.array([[3, 7, 2],
                   [8, 1, 6],
                   [4, 9, 5]])

min_value = np.min(matrix)

max_value = np.max(matrix)

sum_values = np.sum(matrix)

row_min_values = np.min(matrix, axis=1)

column_max_values = np.max(matrix, axis=0)

print("Minimum number:", min_value)
print("Maximum number:", max_value)
print("Sum of all numbers:", sum_values)
print("Minimum numbers for each row:", row_min_values)
print("Maximum numbers for each column:", column_max_values)

Minimum number: 1
Maximum number: 9
Sum of all numbers: 45
Minimum numbers for each row: [2 1 4]
Maximum numbers for each column: [8 9 6]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas





In [ ]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [2]:
import pandas as pd

data = [
    ["Smith", "John", "1985-03-25", 78.5, True],
    ["Doe", "Jane", "1990-07-12", 65.2, False],
    ["Brown", "Emily", "1978-11-03", None, True],
    ["Johnson", "Michael", "2000-05-22", 82.1, True]
]

columns = ["Last Name", "First Name", "Date of Birth", "Weight (kg)", "Medical Insurance"]

df = pd.DataFrame(data, columns=columns)

print(df.dtypes)

print(df)

Last Name             object
First Name            object
Date of Birth         object
Weight (kg)          float64
Medical Insurance       bool
dtype: object
  Last Name First Name Date of Birth  Weight (kg)  Medical Insurance
0     Smith       John    1985-03-25         78.5               True
1       Doe       Jane    1990-07-12         65.2              False
2     Brown      Emily    1978-11-03          NaN               True
3   Johnson    Michael    2000-05-22         82.1               True


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [24]:
import pandas as pd

file_path = "/content/missile_attacks_daily.csv"

df = pd.read_csv(file_path)

print(df.head(20))

          time_start          time_end             model  \
0   2025-01-25 19:00  2025-01-26 09:00    Shahed-136/131   
1   2025-01-24 19:00  2025-01-25 09:30    Shahed-136/131   
2   2025-01-24 18:30  2025-01-24 19:30         X-59/X-69   
3   2025-01-23 21:00  2025-01-24 09:00    Shahed-136/131   
4   2025-01-22 19:00  2025-01-23 09:30    Shahed-136/131   
5   2025-01-23 04:00  2025-01-23 04:30  Iskander-M/KN-23   
6   2025-01-21 19:00  2025-01-22 10:00    Shahed-136/131   
7   2025-01-20 20:00  2025-01-21 09:00    Shahed-136/131   
8   2025-01-20 20:00  2025-01-21 09:00        Iskander-M   
9   2025-01-19 19:00  2025-01-20 08:00    Shahed-136/131   
10  2025-01-19 19:00  2025-01-20 08:00        Iskander-M   
11        2025-01-20        2025-01-20          Orlan-10   
12  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
13  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
14  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
15  2025-01-16 19:00  2025-01-17 09:00  

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [22]:
import pandas as pd

file_path = "/content/missile_attacks_daily.csv"

df = pd.read_csv(file_path)

print(df.head(10))

         time_start          time_end             model  \
0  2025-01-25 19:00  2025-01-26 09:00    Shahed-136/131   
1  2025-01-24 19:00  2025-01-25 09:30    Shahed-136/131   
2  2025-01-24 18:30  2025-01-24 19:30         X-59/X-69   
3  2025-01-23 21:00  2025-01-24 09:00    Shahed-136/131   
4  2025-01-22 19:00  2025-01-23 09:30    Shahed-136/131   
5  2025-01-23 04:00  2025-01-23 04:30  Iskander-M/KN-23   
6  2025-01-21 19:00  2025-01-22 10:00    Shahed-136/131   
7  2025-01-20 20:00  2025-01-21 09:00    Shahed-136/131   
8  2025-01-20 20:00  2025-01-21 09:00        Iskander-M   
9  2025-01-19 19:00  2025-01-20 08:00    Shahed-136/131   

                                        launch_place        target carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
2                                          Black Sea  Odesa oblast     NaN   
3  Primorsko-Akhtarsk and Kursk oblast

14. Отримайте інформацію про форму датафрейму.

In [25]:
df_shape = df.shape

print(df_shape)

(2056, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [26]:
df_info = df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2056 entries, 0 to 2055
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2056 non-null   object 
 1   time_end              2056 non-null   object 
 2   model                 2056 non-null   object 
 3   launch_place          1034 non-null   object 
 4   target                2028 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2053 non-null   float64
 7   destroyed             2056 non-null   int64  
 8   not_reach_goal        164 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       30 non-null     float64
 12  destroyed_details     301 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [27]:
df_numeric_stats = df.describe()

print(df_numeric_stats)

          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2053.000000  2056.000000      164.000000             32.000000   
mean     10.872382     7.647860       21.231707              2.312500   
std      21.605295    14.506397       19.812804              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    35.000000        30.000000  
mean      2.000000         2.766667  
std       1.137593         2.848876  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         3.750000  
max       5.000000        10.000000  


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [ ]:
unique_counts = df.nunique()

print("Number of unique values in each column:\n", unique_counts)

min_unique_column = unique_counts.idxmin()

print(f"\nUnique values and their counts in the column '{min_unique_column}':")
print(df[min_unique_column].value_counts())

18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**Відповідь**

1. Перевірка дублікатів  
2. Перевірка унікальних значень у категоріальних колонках
3. Виправлення типів даних

# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [28]:
df['launched'] = df['launched'].astype('Int64')

print(df.dtypes)
print(df['launched'].head(10))

time_start               object
time_end                 object
model                    object
launch_place             object
target                   object
carrier                  object
launched                  Int64
destroyed                 int64
not_reach_goal          float64
cross_border_belarus    float64
back_russia             float64
still_attacking         float64
destroyed_details        object
launched_details         object
launch_place_details     object
source                   object
dtype: object
0     72
1     61
2      2
3     58
4     92
5      4
6     99
7    131
8      4
9    141
Name: launched, dtype: Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [29]:
threshold = len(df) * 0.3

df_cleaned = df.dropna(axis=1, thresh=threshold)

print("DataFrame shape after column removal:", df_cleaned.shape)
print("Remaining columns:\n", df_cleaned.columns)

Форма датафрейму після видалення колонок: (2056, 8)
Залишилися колонки:
 Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'launched',
       'destroyed', 'source'],
      dtype='object')


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [34]:
import pandas as pd

file_path = "/content/missile_attacks_daily.csv"
df = pd.read_csv(file_path)

df['time_start'] = pd.to_datetime(df['time_start'], errors='coerce', infer_datetime_format=True)
df['time_end'] = pd.to_datetime(df['time_end'], errors='coerce', infer_datetime_format=True)

print("Missing values after conversion:\n", df[['time_start', 'time_end']].isna().sum())

df = df.dropna(subset=['time_start', 'time_end'])

df['attack_duration'] = (df['time_end'] - df['time_start']).dt.total_seconds() / 60

initial_rows = len(df)

df = df.drop_duplicates()

df = df[df['attack_duration'] > 0]

df.reset_index(drop=True, inplace=True)

final_rows = len(df)
removed_rows = initial_rows - final_rows

print(f"Number of removed rows: {removed_rows}")
print(f"Final shape of the DataFrame: {df.shape}")

Missing values after conversion:
 time_start    1446
time_end       678
dtype: int64
Number of removed rows: 162
Final shape of the DataFrame: (445, 17)


<ipython-input-34-59cff4a07625>:6: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['time_start'] = pd.to_datetime(df['time_start'], errors='coerce', infer_datetime_format=True)
<ipython-input-34-59cff4a07625>:7: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['time_end'] = pd.to_datetime(df['time_end'], errors='coerce', infer_datetime_format=True)


**місце для текстової відповіді**

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [35]:
missing_rows = df[df.isnull().any(axis=1)]

print("Rows with missing values:")
print(missing_rows)

print(f"\nTotal rows with missing values: {len(missing_rows)}")

Rows with missing values:
             time_start            time_end           model  \
0   2025-01-25 19:00:00 2025-01-26 09:00:00  Shahed-136/131   
1   2025-01-24 19:00:00 2025-01-25 09:30:00  Shahed-136/131   
2   2025-01-24 18:30:00 2025-01-24 19:30:00       X-59/X-69   
3   2025-01-23 21:00:00 2025-01-24 09:00:00  Shahed-136/131   
4   2025-01-22 19:00:00 2025-01-23 09:30:00  Shahed-136/131   
..                  ...                 ...             ...   
440 2022-10-06 15:00:00 2022-10-06 20:00:00       Mohajer-6   
441 2022-10-06 09:00:00 2022-10-06 11:30:00  Shahed-136/131   
442 2022-10-06 09:00:00 2022-10-06 11:30:00       Mohajer-6   
443 2022-10-02 00:00:00 2022-10-02 02:00:00  Shahed-136/131   
444 2022-09-29 23:00:00 2022-09-29 23:59:00  Shahed-136/131   

                                          launch_place  \
0    Primorsko-Akhtarsk and Kursk oblast and Bryans...   
1    Primorsko-Akhtarsk and Kursk oblast and Bryans...   
2                                          